### ISSUE TITLE
[Bug] Unable to access Macros fully (Patch 10.0.0.46340)

### ISSUE THREAD

**Issue by Kornukopian** [Gethe/Aurora#52] opened 2022-10-29 17:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

- Macros show in window (in icon form), but the macro text does not appear for specific macros when selected.
- "Save" and "Cancel" buttons show below the chat window.
- Icon for particular macro - as well as the "Change Name/Icon" button - appears above the macro window.

### Expected Behavior

Expected Macros window to open, with macro commands showing normally.

### Steps To Reproduce

1. Type "/m" in chat window to open Macros window

### Additional context

Image of issue:
![image](https://user-images.githubusercontent.com/116970552/198844395-56060cdb-30b2-43b5-b687-5fc7a9a4bd54.png)

Bugsack returns the following:
`20x ...urora/Skin/Interface/FrameXML/ItemButtonTemplate.lua:305: attempt to concatenate a nil value
[string "@Interface/AddOns/Aurora/Skin/Interface/FrameXML/ItemButtonTemplate.lua"]:305: in function `PopupButtonTemplate'
[string "@Interface/AddOns/Aurora/Skin/Interface/AddOns/Blizzard_MacroUI.lua"]:28: in function `?'
[string "@Interface/AddOns/Aurora/Skin/util.lua"]:149: in function `CheckTemplate'
[string "@Interface/AddOns/Aurora/Skin/Interface/SharedXML/Pools.lua"]:26: in function <...ace/AddOns/Aurora/Skin/Interface/SharedXML/Pools.lua:20>
[string "=[C]"]: in function `Acquire'
[string "@Interface/SharedXML/Scroll/ScrollBoxListView.lua"]:41: in function `factory'
[string "@Interface/SharedXML/Scroll/ScrollBoxListView.lua"]:343: in function `elementFactory'
[string "@Interface/SharedXML/Scroll/ScrollBoxListView.lua"]:251: in function `AcquireInternal'
[string "@Interface/SharedXML/Scroll/ScrollBoxListView.lua"]:300: in function `AcquireRange'
[string "@Interface/SharedXML/Scroll/ScrollBoxListView.lua"]:718: in function `Rebuild'
[string "@Interface/SharedXML/Scroll/ScrollBoxListView.lua"]:778: in function `ValidateDataRange'
[string "@Interface/SharedXML/Scroll/ScrollBox.lua"]:647: in function `Update'
...
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3150: in function <Interface/FrameXML/UIParent.lua:3129>
[string "=[C]"]: in function `ShowUIPanel'
[string "@Interface/AddOns/Blizzard_MacroUI/Blizzard_MacroUI.lua"]:17: in function `MacroFrame_Show'
[string "@Interface/FrameXML/UIParent.lua"]:877: in function `ShowMacroFrame'
[string "@Interface/FrameXML/ChatFrame.lua"]:2190: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5219: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4883: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4919: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:127_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:127_OnEnterPressed"]:1>

Locals:
CheckButton = Button {
 0 = <userdata>
 Highlight = Texture {
 }
 OnBackdropLoaded = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:174
 SelectedTexture = Texture {
 }
 SetBackdropOptions = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:364
 OnDragStart = <function> defined @Interface/AddOns/Blizzard_MacroUI/Blizzard_MacroUI.lua:40
 SetBackdropBorderColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:289
 OnClick = <function> defined @Interface/AddOns/Blizzard_MacroUI/Blizzard_MacroUI.lua:31
 GetSelectionIndex = <function> defined @Interface/SharedXML/Selector/Blizzard_SelectorUI.lua:113
 GetBackdropTexture = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:333
 SetSelectionIndex = <function> defined @Interface/SharedXML/Selector/Blizzard_SelectorUI.lua:108
 selectorFrame = Frame {
 }
 ApplyBackdrop = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:192
 GetSelectorFrame = <function> defined @Interface/SharedXML/Selector/Blizzard_SelectorUI.lua:137
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 selectionIndex = 1
 GetBackdropBorderColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:305
 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347
 TopLeftCorner = Texture {
 }
 BottomRightCorner = Texture {
 }
 GetSelection = <function> defined @Interface/SharedXML/Selector/Blizzard_SelectorUI.lua:133
 SetBackdropGradient = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:311
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 SetBackdropOption = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:342
 Center = Texture {
 }
 RightEdge = Texture {
 }
 SetBackdropLayer = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:319
 GetBackdropOption = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:358
 BottomEdge = Texture {
 }
 UpdateSelectedTexture = <function> defined @Interface/SharedXML/Selector/Blizzard_SelectorUI.lua:125
 GetIconTexture = <function> defined @Interface/SharedXML/Selector/Blizzard_SelectorUI.lua:121
 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278
 Icon = Texture {
 }
 BottomLeftCorner = Texture {
 }
 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188
 TopRightCorner = Texture {
 }
 OnLoad = <function> defined @Interface/AddOns/Blizzard_MacroUI/Blizzard_MacroUI.lua:27
 TopEdge = Texture {
 }
 _backdropInfo = <table> {
 }
 backdropInfo = <table> {
 }
 SetBackdrop = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:246
 GetBackdropColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:285
 GetBackdropLayer = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:328
 Name = FontString {
 }
 SetIconTexture = <function> defined @Interface/SharedXML/Selector/Blizzard_SelectorUI.lua:117
 SetupPieceVisuals = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:177
 SetBackdropColor = <function> defined @Interface/AddOns/Aurora/Skin/backdrop.lua:275
 LeftEdge = Texture {
 }
 Init = <function> defined @Interface/SharedXML/Selector/Blizzard_SelectorUI.lua:104
}
bg = Texture {
 0 = <userdata>
}
(*temporary) = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @Interface/FrameXML/ActionButton.lua:82
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 SettingsSliderOptionsMixin = <table> {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Hide Bar Art"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 773
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_`

**Comment by Gethe** [comment] 2022-10-29 18:58
duplicate of #47

**Closed** 2022-10-29 18:58 UTC
Labels: bug
