### ISSUE TITLE
[Bug] Can't list any LFG group if Aurora is enabled (and no BNet authenticator) on Retail 10.2.7

### ISSUE THREAD

**Issue by Heregellas** [Gethe/Aurora#117] opened 2024-05-28 09:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail 10.2.7

### Current Behavior

Hello !

So, when creating a LFG group (whether it's a dungeon one, or a raid one), if you don't have a BNet authenticator, usually you just can't edit the fields, but they are auto-filled with a generic name, and you can list the group.
However, with Aurora enabled, the title is not auto-filled, thus the group cannot be created under any circumstances.
Here are 2 screenshots where you can see the difference between the behavior with and without Aurora, the button to create a group being greyed-out with the addon enabled, and zero way to create it unfortunately.

**Dungeon** : https://i.gyazo.com/8a2d56ce0bc3ff54122291015ad58c54.png
**Raid** : https://i.gyazo.com/a4644ef94b5bfdc004a6beec70601532.png

I know one other easy fix would be to activate authenticator, but still, it should normally auto-fill these fields and let us be able to create the group regardless.
Curiously enough, there is no LUA error tied to this behavior.

(The "Goal" and "Playstyle" dropdown lists are not working too it seems, as we can see on these screenshots)

Thanks a lot for your time when you'll check this issue !

**Comment by arnvid** [comment] 2024-05-29 00:01
This caused by an anti taint fix that I put into 10.2.7.1. The taint is caused by Blizzard. I will check if my "backup" wow account have authenticator to test this.. but this is a bit "damned if you do damned if you dont" situation. And the reason there is no taint and no error is that the fix is to overwrite a blizzard function :)

https://github.com/Gethe/Aurora/commit/92b2fe86443240145ce90e543fe636a103490263

This is the fix if you want to try to remove it. And see if you get the lua error/taint instead

**Comment by arnvid** [comment] 2024-06-24 20:38
Fix is in 10.2.7.4

**Closed by arnvid** 2024-06-24 20:38 UTC
Labels: bug
