### ISSUE TITLE
[Bug] Tooltip Backdrop

### ISSUE THREAD

**Issue by DreamsUnderStars** [Gethe/Aurora#39] opened 2022-06-21 16:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

On logging in I get this error, tooltip addons were giving this error as well.

```
Message: ...\Skin\Interface\SharedXML\SharedUIPanelTemplates.lua:395: attempt to index local 'Frame' (a nil value)
Time: Tue Jun 21 12:52:00 2022
Count: 1
Stack: ...\Skin\Interface\SharedXML\SharedUIPanelTemplates.lua:395: attempt to index local 'Frame' (a nil value)
[string "@Interface\AddOns\Aurora\Skin\Interface\SharedXML\SharedUIPanelTemplates.lua"]:395: in function `NineSlicePanelTemplate'
[string "@Interface\AddOns\Aurora\Skin\Interface\SharedXML\SharedUIPanelTemplates.lua"]:504: in function `TooltipBackdropTemplate'
[string "@Interface\AddOns\totalRP3\libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua"]:1704: in function <...3\libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua:1700>
[string "@Interface\AddOns\totalRP3\libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua"]:1714: in function <...3\libs\MSA-DropDownMenu-1.0\MSA-DropDownMenu-1.0.lua:1711>

Locals: Frame = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'Frame' (a nil value)"
Hook = <table> {
 LFDQueueFrameRandomCooldownFrame_Update = <function> defined @Interface\AddOns\Aurora\Skin\Interface\FrameXML\LFDFrame.lua:13
 GuildMicroButtonMixin = <table> {
 }
 PVPReadyPopupMixin = <table> {
 }
 ChallengesKeystoneFrameMixin_OnKeystoneSlotted = <function> defined @Interface\AddOns\Aurora\Skin\Interface\AddOns\Blizzard_ChallengesUI.lua:26
 QuestObjectiveSetupBlockButton_AddRightButton = <function> defined @Interface\AddOns\Aurora\Skin\Interface\AddOns\Blizzard_ObjectiveTracker.lua:21
 FCF_SetButtonSide = <function> defined @Interface\AddOns\Aurora\Skin\Interface\FrameXML\FloatingChatFrame.lua:40
 QuestFrameProgressItems_Update = <function> defined @Interface\AddOns\Aurora\Skin\Interface\FrameXML\QuestFrame.lua:13
 OrderHallMission = <table> {
 }
 HelpPlate_GetButton = <function> defined @Interface\AddOns\Aurora\Skin\Interface\FrameXML\TutorialFrame.lua:69
 LFGListApplicationViewer_UpdateRoleIcons = <function> defined @Interface\AddOns\Aurora\Skin\Interface\FrameXML\LFGList.lua:91
 ChallengesKeystoneFrameMixin_Reset = <function> defined @Interface\AddOns\Aurora\Skin\Interface\AddOns\Blizzard_ChallengesUI.lua:22
 EmbeddedItemTooltip_PrepareForSpell = <function> defined @Interface\AddOns\Aurora\Skin\Interface\FrameXML\GameTooltip.lua:23
 NavBar_CheckLength = <function> defined @Interface\AddOns\Aurora\Skin\Interface\FrameXML\NavigationBar.lua:17
 BossBanner_ConfigureLootFrame = <function> defined @Interface\AddOns\Aurora\Skin\Interface\FrameXML\BossBannerToast.lua:12
 AchievementButton_GetMiniAchievement = <function> defined @Interface\AddOns\Aurora\Skin\Interface\AddOns\Blizzard_AchievementUI.lua:85
 AchievementButton_UpdatePlusMinusTexture = <function> defined @Interface\AddOns\Aurora\Skin\Interface\AddOns\Blizzard_AchievementUI.lua:39
 AchievementFrameStats_SetStat = <function> defined @Interface\AddOns\Aurora\Skin\Interface\AddOns\Blizzard_AchievementUI.lua:116
 NewPvpSeasonMixin = <table> {
 }
 UIDropDownMenuButton_OnClick = <function> defined @Interface\AddOns\Aurora\Skin\Interface\SharedXML\UIDropDownMenu.lua:104
 PartyPoseRewardsMixin = <table> {
 }
 LFGListUtil_SetSearchEntryTooltip = <function> defined @Interface\AddOns\Aurora\Skin\Interface\FrameXML\LFGList.lua:130
 LFGCooldownCover_Update = <function> defined @Interface\AddOns\Aurora\Skin\Interface\FrameXML\LFGFrame.lua:70
 PetStable_Update = <function> defined @Interface\AddOns\Aurora\Skin\Interface\FrameXML\PetStable.lua:21
 CovenantSanctumMixin = <table> {
 }
 RaceFilter_OnHide = <function> defined @Interface\AddOns\Aurora\Skin\Interface\AddOns\Blizzard_ArchaeologyUI.lua:16
 UIWidgetManagerMixin = <table> {
 }
 AuctionHouseFavoritesSearchButtonMixin = <table> {
 }
 GarrisonFollowerButton_AddAbility = <function> defined @Interface\AddOns\Aurora\Skin\Interface\AddOns\Blizzard_GarrisonTemplates.lua:29
 CommunitiesTicketManagerDialogMixin = <table> {
 }
 CovenantRenownMixin = <table> {
 }
 EncounterJour
```

**Comment by Gethe** [comment] 2022-10-06 23:29
Duplicate of #34 and #29

**Closed by Gethe** 2022-10-06 23:29 UTC
Labels: bug
