### ISSUE TITLE
[Bug]ContainerFrame.lua:25: attempt to call method 'GetBackdropColor' (a nil value)

### ISSUE THREAD

**Issue by CrisReus** [Gethe/Aurora#70] opened 2022-11-22 12:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Game Client

Retail

### Current Behavior

2x ...ns/Aurora/Skin/FrameXML/ContainerFrame.lua:25: attempt to call method 'GetBackdropColor' (a nil value)
[string "@Aurora/Skin/FrameXML/ContainerFrame.lua"]:25: in function <...ns/Aurora/Skin/FrameXML/ContainerFrame.lua:22>
[string "=[C]"]: in function `ContainerFrame_GenerateFrame'
[string "@FrameXML/ContainerFrame.lua"]:206: in function <FrameXML/ContainerFrame.lua:200>
[string "@FrameXML/ContainerFrame.lua"]:222: in function `OpenBag'
[string "@FrameXML/ContainerFrame.lua"]:1832: in function <FrameXML/ContainerFrame.lua:1825>
[string "@FrameXML/ContainerFrame.lua"]:1856: in function `OpenAllBags'
[string "@ExtVendor/ExtVendor.lua"]:208: in function `ExtVendor_OnUpdate'
[string "*ExtVendor.xml:18_OnUpdate"]:1: in function <[string "*ExtVendor.xml:18_OnUpdate"]:1>

Locals:
frame = ContainerFrame6 {
 0 = <userdata>
 CheckAuthenticatorSlotsHelpTip = <function> defined @FrameXML/ContainerFrame.lua:1062
 UpdateMoneyFrame = <function> defined @FrameXML/ContainerFrame.lua:730
 UpdateFilterIcon = <function> defined @FrameXML/ContainerFrame.lua:922
 GetTitleText = <function> defined @SharedXML/PortraitFrame.lua:28
 GetPaddingWidth = <function> defined @FrameXML/ContainerFrame.lua:849
 SetPortraitTexCoord = <function> defined @SharedXML/PortraitFrame.lua:87
 size = 20
 CheckUpdateDynamicContents = <function> defined @FrameXML/ContainerFrame.lua:822
 UpdateIfShown = <function> defined @FrameXML/ContainerFrame.lua:1048
 GetBagID = <function> defined @FrameXML/ContainerFrame.lua:746
 TitleContainer = Frame {
 }
 UpdateItemContextMatching = <function> defined @FrameXML/ContainerFrame.lua:1080
 LayoutAddSlots = <function> defined @FrameXML/ContainerFrame.lua:1088
 SetTitle = <function> defined @SharedXML/PortraitFrame.lua:36
 OnCloseClicked = <function> defined @FrameXML/ContainerFrame.lua:726
 PortraitButton = ContainerFrame6PortraitButton {
 }
 GetInitialItemAnchor = <function> defined @FrameXML/ContainerFrame.lua:863
 CalculateHeight = <function> defined @FrameXML/ContainerFrame.lua:833
 Update = <function> defined @FrameXML/ContainerFrame.lua:989
 SetPortraitAtlasRaw = <function> defined @SharedXML/PortraitFrame.lua:83
 CancelRefresh = <function> defined @FrameXML/ContainerFrame.lua:963
 MatchesBagID = <function> defined @FrameXML/ContainerFrame.lua:754
 UpdateAddSlots = <function> defined @FrameXML/ContainerFrame.lua:1084
 IsExtended = <function> defined @FrameXML/ContainerFrame.lua:567
 SetTitleFormatted = <function> defined @SharedXML/PortraitFrame.lua:40
 NineSlice = Frame {
 }
 ClickableTitleFrame = Button {
 }
 CalculateWidth = <function> defined @FrameXML/ContainerFrame.lua:829
 SetPortraitTextureSizeAndOffset = <function> defined @SharedXML/PortraitFrame.lua:95
 Items = <table> {
 }
 GetRows = <function> defined @FrameXML/ContainerFrame.lua:790
 AddItemsForRefresh = <function> defined @FrameXML/ContainerFrame.lua:970
 SetPortraitShown = <function> defined @SharedXML/PortraitFrame.lua:91
 GetExtraRows = <function> defined @FrameXML/ContainerFrame.lua:782
 EnumerateValidItems = <function> defined @FrameXML/ContainerFrame.lua:599
 SetPortraitTextureRaw = <function> defined @SharedXML/PortraitFrame.lua:79
 GetBagSize = <function> defined @FrameXML/ContainerFrame.lua:555
 CalculateExtraHeight = <function> defined @FrameXML/ContainerFrame.lua:840
 SetTitleMaxLinesAndHeight = <function> defined @SharedXML/PortraitFrame.lua:49
 SetTitleColor = <function> defined @SharedXML/PortraitFrame.lua:32
 FilterDropDown = ContainerFrame6FilterDropDown {
 }
 UpdateItems = <function> defined =[C]:-1
 UpdateSearchResults = <function> defined @FrameXML/ContainerFrame.lua:604
 FilterIcon = Button {
 }
 EnumerateItems = <function> defined @FrameXML/ContainerFrame.lua:587
 Background1Slot = ContainerFrame6Background1Slot {
 }
 GetPaddingHeight = <function> defined @FrameXML/ContainerFrame.lua:844
 CloseButton = Button {
 }
 UpdateFrameSize = <function> defined @FrameXML/ContainerFrame.lua:853
 Bg = Frame {
 }
 GetContainedBagIDs = <function> defined @FrameXML/ContainerFrame.lua:750
 canUseForReagentBag = true
 SetBorder = <function> defined =[C]:-1
 layoutType = "HeldBagLayout"
 onCloseCallback = <function> defined @FrameXML/ContainerFrame.lua:720
 GetFirstButtonOffsetY = <function> defined @FrameXML/ContainerFrame.lua:770
 CanUseForBagID = <function> defined @FrameXML/ContainerFrame.lua:758
 IsBankBag = <function> defined @FrameXML/ContainerFrame.lua:583
 PortraitContainer = Frame {
 }
 SetPor

**Comment by Gethe** [comment] 2022-11-28 20:45
Duplicate of #66

**Closed by Gethe** 2022-11-28 20:45 UTC
Labels: bug
